import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { testimonials } from "@/lib/data";

export default function LandingPage() {
  return (
    <main className="luxury-gradient min-h-screen overflow-hidden">
      <Navbar />
      <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28">
        <div>
          <div className="mb-6 inline-flex rounded-full border border-blue-300/20 bg-blue-500/10 px-4 py-2 text-sm font-bold text-blue-100">✦ AI-Powered Scholarship Matching</div>
          <h1 className="font-display max-w-4xl text-6xl font-semibold leading-[.95] tracking-tight text-white md:text-8xl">Your Scholarship. <span className="gold-text">Found in 60 Seconds.</span></h1>
          <p className="mt-6 max-w-2xl text-xl leading-8 text-slate-300">Stop wasting hours searching. Tell us your profile — our AI matches you with grants you&apos;ll actually win.</p>
          <div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/search" className="rounded-full bg-blue-600 px-7 py-4 text-center font-black shadow-2xl shadow-blue-600/30 hover:bg-blue-500">Find My Scholarship →</Link><a href="#how" className="rounded-full border border-white/15 px-7 py-4 text-center font-black hover:bg-white/10">See How It Works</a></div>
          <div className="mt-10 inline-flex items-center gap-4 rounded-3xl border border-white/10 bg-white/5 p-4"><span className="text-4xl font-black text-amber-300">12,847</span><span className="text-slate-300">scholarships analyzed</span></div>
        </div>
        <div className="float glass blue-glow rounded-[2rem] p-6"><div className="rounded-3xl bg-[#071225] p-5"><div className="mb-5 flex items-center justify-between"><span className="font-display text-2xl">Live Match Preview</span><span className="rounded-full bg-emerald-500/20 px-3 py-1 text-sm text-emerald-200">87% fit</span></div>{["DAAD Study Scholarship", "Global Excellence Award", "Future Leaders Grant"].map((item, i) => <div key={item} className="mb-3 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between font-bold"><span>{item}</span><span className="text-blue-300">#{i + 1}</span></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-600" style={{ width: `${92 - i * 8}%` }} /></div></div>)}</div></div>
      </section>
      <section className="border-y border-white/10 bg-white/[.03]"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 text-center sm:grid-cols-3 sm:px-6 lg:px-8"><Stat value="500+" label="Scholarships" /><Stat value="40+" label="Countries" /><Stat value="$2.3B" label="in Grants" /></div></section>
      <section id="how" className="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8"><div className="mb-12 max-w-2xl"><p className="font-bold uppercase tracking-[.3em] text-blue-300">How it works</p><h2 className="font-display mt-3 text-5xl">From profile to shortlist in three steps.</h2></div><div className="grid gap-5 md:grid-cols-3">{[["01", "Fill Your Profile", "GPA, country, tests, field, background — completed in 2 minutes."], ["02", "AI Analyzes 500+ Grants", "We compare eligibility, deadlines, requirements, and realistic probability."], ["03", "Apply with Confidence", "Get strengths, gaps, next steps, and official application links."]].map(([n, title, text]) => <div key={n} className="glass rounded-3xl p-7"><div className="font-display text-6xl text-blue-400/70">{n}</div><h3 className="mt-6 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></div>)}</div></section>
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8"><h2 className="font-display mb-10 text-5xl">Students already winning.</h2><div className="grid gap-5 md:grid-cols-3">{testimonials.map((item) => <div key={item.name} className="glass rounded-3xl p-6"><div className="mb-5 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-blue-600 font-black">{item.avatar}</div><div><div className="font-bold">{item.name}</div><div className="text-sm text-slate-400">{item.country}</div></div></div><p className="leading-7 text-slate-300">“{item.quote}”</p><div className="mt-5 rounded-full bg-amber-500/15 px-4 py-2 text-sm font-bold text-amber-200">Won: {item.won}</div></div>)}</div></section>
      <section id="pricing" className="mx-auto max-w-5xl px-4 pb-24 sm:px-6 lg:px-8"><h2 className="font-display text-center text-5xl">Simple pricing for students.</h2><div className="mt-10 grid gap-5 md:grid-cols-2"><Plan name="Free" price="$0" features={["3 searches/month", "7 AI matches", "Profile feedback"]} /><Plan featured name="Pro" price="$9/mo" features={["Unlimited searches", "Email deadline alerts", "Saved scholarship tracker", "Priority AI advice"]} /></div></section>
      <footer className="border-t border-white/10 px-4 py-10 text-center text-slate-400">© 2026 Uni Match. Built for ambitious international students.</footer>
    </main>
  );
}
function Stat({ value, label }: { value: string; label: string }) { return <div><div className="font-display text-4xl text-white">{value}</div><div className="mt-1 text-slate-400">{label}</div></div>; }
function Plan({ name, price, features, featured }: { name: string; price: string; features: string[]; featured?: boolean }) { return <div className={`rounded-[2rem] border p-7 ${featured ? "border-amber-300/40 bg-amber-500/10" : "border-white/10 bg-white/5"}`}><h3 className="text-2xl font-black">{name}</h3><div className="font-display my-5 text-5xl">{price}</div><ul className="space-y-3 text-slate-300">{features.map((f) => <li key={f}>✓ {f}</li>)}</ul><Link href="/search" className="mt-7 block rounded-full bg-blue-600 px-5 py-3 text-center font-black hover:bg-blue-500">Start Matching</Link></div>; }
